CREATE TABLE departments
(
    id                int8 generated by default as identity,
    name              varchar(255)  not null,
    description       varchar(255) not null,
    phone_number      varchar(255)  not null,
    date_of_formation timestamp    not null,

    primary key (id)
);

CREATE TABLE employees
(
    id                 int8 generated by default as identity,
    full_name          varchar(255),
    date_of_birth      timestamp   not null,
    phone_number       varchar(255) not null,
    email_address      varchar(255) not null,
    position           varchar(30) not null,
    date_of_employment timestamp   not null,
    department_id      int8 default null,

    primary key (id),
    foreign key (department_id) references departments (id)
);

