create table users
(
    id int8 generated by default as identity,
    email varchar(255) not null unique,
    first_name varchar(50) not null,
    last_name varchar(100) not null,
    password varchar(255) not null,
    role varchar(20) not null default 'USER',
    status varchar(20) default 'ACTIVE',
    primary key (id)
);